name: quickcheck-string-random
version: 0.1.2.0
synopsis: Helper to build generators with Text.StringRandom
description: ! 'Define a generator of Text that matches regular

  expressions. This package is useful for creating Arbitrary

  instances of Text type restricted by newtype.'
category: Test
author: Masahiro Honma
maintainer: hiratara@cpan.org
copyright: Copyright (C) 2016- hiratara
license: BSD3
github: hiratara/hs-string-random
tested-with: GHC==8.0.1
library:
  source-dirs: src
  exposed-modules:
  - Test.QuickCheck.StringRandom
  dependencies:
  - base >=4.9 && <5
  - QuickCheck >=2.8.2 && <2.14
  - string-random ==0.1.*
  - text >=1.2.2.1 && <1.3
tests:
  quickcheck-string-random-test:
    main: quickcheck-string-random-test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - QuickCheck
    - quickcheck-string-random
    - tasty
    - tasty-quickcheck
    - text
