name: string-random
version: 0.1.0.0
synopsis: A library for generating random string from a regular experession
description: ! 'With this package you can generate random strings from

  regular expressions. If you are using QuickCheck, you can

  also check the quickcheck-string-random package.'
category: Text
author: Masahiro Honma
maintainer: hiratara@cpan.org
copyright: Copyright (C) 2016- hiratara
license: BSD3
github: hiratara/hs-string-random
tested-with: GHC==8.0.1
library:
  source-dirs: src
  exposed-modules:
  - Text.StringRandom
  - Text.StringRandom.Parser
  dependencies:
  - base >=4.9 && <5
  - attoparsec >=0.13.1 && <0.14
  - containers >=0.5.7.1 && <0.6
  - random >=1.1 && <1.2
  - text >=1.2.2.1 && <1.3
  - transformers >=0.5.2.0 && <0.6
executables:
  hstrrand:
    main: hstrrand.hs
    source-dirs: app
    ghc-options:
    - -O2
    - -threaded
    - -Wall
    dependencies:
    - base >=4.9 && <5
    - optparse-applicative
    - string-random
    - text
tests:
  string-random-quickcheck:
    main: string-random-quickcheck.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pcre-heavy
    - QuickCheck
    - string-random
    - tasty
    - tasty-quickcheck
    - text
  string-random-test:
    main: string-random-test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bytestring
    - pcre-heavy
    - string-random
    - tasty
    - tasty-hunit
    - text
