name: Haskell CI

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10']
        cabal: ['2.4', '3.0', '3.2']
        os: [ubuntu-latest, macOS-latest]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8
            cabal: 2.4
          - ghc: 8.10
            cabal: 2.4

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal v2-build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: cabal v2-build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal v2-test all
